# Generated by Django 4.2.1 on 2023-05-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_categories_task_category_feedback'),
        ('replays', '0002_replay_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='tasks.task'),
        ),
    ]
