# Generated by Django 4.2.1 on 2023-05-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_alter_task_categories'),
        ('offers', '0002_alter_offer_executor'),
        ('burse', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
