# Generated by Django 4.2.1 on 2023-05-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burse', '0001_initial'),
        ('tasks', '0002_task_categories_alter_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='burse.category'),
        ),
    ]
